backend:
  name: git-gateway
  repo: MattGiertl/kafarna-cokolif
  branch: develop

media_folder: static/images
public_folder: images

collections:
  - label: "Stránky"
    name: pages
    files:
      - label: "Hlavní stránka"
        name: mainpageContent
        file: "src/data/mainpage.json"
        fields:
          - { label: Úvodný obrázek, name: splashImage, widget: image }
          - { label: O Kafárně, name: aboutUs, widget: text }
          - { label: O nás - obrázek, name: aboutUsImage, widget: image }

  - label: "Menu"
    name: "menu"
    folder: "/src/data/menu"
    fields:
      - { label: "Položky menu", name: "title", default: "Položky menu" }
      - {
          label: "Sekce menu",
          name: "menuSections",
          widget: list,
          allow_add: true,
          fields:
            [
              { label: "Název hlavičky", name: "title" },
              { label: "Obsah", name: "content", widget: markdown },
            ],
        }
