backend:
  name: git-gateway
  repo: MattGiertl/kafarna-cokolif
  branch: menu-rework

media_folder: static/images
public_folder: images

collections:
  - label: "Stránky"
    name: pages
    files:
      - label: "Hlavní stránka"
        name: mainpageContent
        file: "src/data/mainpage.json"
        fields:
          - { label: Úvodný obrázek, name: splashImage, widget: image }
          - { label: O Kafárně, name: aboutUs, widget: text }
          - { label: O nás - obrázek, name: aboutUsImage, widget: image }

  - label: "Menu"
    name: "menu"
    create: true
    folder: "/src/data/menu"
    identifier_field: menuSections
    fields:
      - {
          label: "Sekce menu",
          name: "menuSections",
          widget: list,
          allow_add: true,
          fields:
            [
              { label: "Název hlavičky", name: "title", widget: string },
              { label: "Obsah", name: "content", widget: markdown },
            ],
        }
