backend:
  name: github
  repo: MattGiertl/kafarna-cokolif

media_folder: static/assets
public_folder: assets

collections:
  - label: "Obsah stránky"
    name: "pageContent"
    format: "json"
    files:
      - label: "Obsah stránky"
        name: "page"
        create: true
          allow_add: true
        format: "json"
        file: "site/content/content.json"
        fields:
          - { label: O kafárně, name: about, widget: text }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
