backend:
  name: github
  branch: master
  repo: MattGiertl/kafarna-cokolif

media_folder: static/images
public_folder: images

collections:
  - label: "Stránky"
    name: pages
    files:
      - label: "Hlavní stránka"
        name: mainpageContent
        file: "src/data/mainpage.json"
        fields:
          - { label: Úvodný obrázek, name: splashImage, widget: image }
          - { label: O Kafárně, name: aboutUs, widget: text }
          - { label: Recenze, name: review, widget: text }
          - { label: Autor recenze, name: reviewAuthor, widget: string }
          - { label: O nás - obrázek, name: aboutUsImage, widget: image }
          - {
              label: Kde nás můžete najít - obrázek,
              name: whereToFindUsImage,
              widget: image,
            }
  - label: "Menu"
    name: menu
    create: true
    files:
      - label: "Jídelníček"
        name: eatmenu
        file: "src/data/eatmenu.json"
        create: true
        fields:
          - { label: "Test", name: "test", widget: string }
          - { label: "Do pice", name: "jeblina", widget: string }

      - label: "Nápojový lístek"
        name: drinkmenu
        file: "src/data/drinkmenu.json"
        create: true
        fields:
          - { label: "TestB", name: "testNB", widget: string }
          - { label: "Do picea", name: "jeblinaa", widget: string }
