backend:
  name: github
  repo: MattGiertl/kafarna-cokolif

media_folder: static/assets
public_folder: assets

collections:
  - name: menu
    label: Menu
    folder: menu
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: price, label: Price }
